test

diff --git a/.github/workflows/sensor_submission.yml b/.github/workflows/sensor_submission.yml
--- a/.github/workflows/sensor_submission.yml
+++ b/.github/workflows/sensor_submission.yml
@@ -64,6 +64,30 @@ jobs:
               exit 1
             fi
 
+      - name: Generate csv
+        if: success()
+        continue-on-error: true
+        run: |
+          python3 scripts/generate_csv.py
+          if [ $? -ne 0 ]; then
+            echo "generate_csv_error<<EOF" >> $GITHUB_ENV
+              cat $ERROR_FILE >> $GITHUB_ENV
+              echo "EOF" >> $GITHUB_ENV
+              exit 1
+            fi
+
+      - name: Generate yaml
+        if: success()
+        continue-on-error: true
+        run: |
+          python3 scripts/generate_yaml.py
+          if [ $? -ne 0 ]; then
+            echo "generate_yaml_error<<EOF" >> $GITHUB_ENV
+              cat $ERROR_FILE >> $GITHUB_ENV
+              echo "EOF" >> $GITHUB_ENV
+              exit 1
+            fi
+
       - name: Generate markdown/documentation
         if: success()
         continue-on-error: true
@@ -113,6 +137,9 @@ jobs:
             }
             if (process.env.generate_csv_error) {
               errors.push(`Error in generate_csv.py:\n${process.env.generate_csv_error}`);
+            }
+            if (process.env.generate_yaml_error) {
+              errors.push(`Error in generate_yaml.py:\n${process.env.generate_yaml_error}`);
             }
             if (process.env.generate_markdown_error) {
               errors.push(`Error in generate_markdown.py:\n${process.env.generate_markdown_error}`);
